### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by JeffreyConnected** [marlon360/webxr-handtracking#1]
These examples don't work on my Quest. I don't see this in my Oculus setting "Enable automatic switching between hands and controller in Oculus Settings" Also, how do you "Enter VR with controller"?

**Comment by marlon360** [comment]
Hey!

First make sure you have the latest Oculus Browser version (10.2).

To enable "Auto Enable Hands or Controllers":
1. Open the Oculus Menu (if not visible press Oculus button on the controller)
2. Press the gear icon to open the settings menu
3. Go to **Device** (on the left)
4. choose **Hands and Controllers**
5. enable **Auto Enable Hands or Controllers**

>  how do you "Enter VR with controller"?

Although this is a hand tracking demo, you cannot start the experience with your hands.
Grab your controllers and press the trigger when hovering "VR" or "Enter VR".
Then you can put your controllers down and look at your hands to enable hand tracking.
After a few seconds hand tracking gets automatically enabled.

Let me know if this works, after that I will close the issue.

**Comment by JeffreyConnected** [comment]
Today it's working =) Yesterday, I couldn't get it to work because there was no "VR" or "Enter VR" button on the bottom right corner. Anyway, thanks for responding. These examples are super cool!
